# Generated by Django 5.0.6 on 2024-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='inboxes', to='accounts.message'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ebooks',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='ebooks.ebook'),
        ),
    ]
